apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kuber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-kuber
  template:
    metadata:
      labels:
        app: demo-kuber
    spec:
      containers:
        - name: demo-kuber
          image:  6f0e983f261a/demo-kuber
          ports:
            - containerPort: 8080